#!/bin/bash

if [ ! $1 ]; then
	echo "USAGE: ./runthis <script to run in debian environment>"
	exit 1
fi


script="$1"


docker=$(which docker 2> /dev/null)
if [ $? = 0 ]; then
	echo "Docker was found"
	docker=$docker
else
	docker="missing"
fi

podman=$(which podman 2> /dev/null)
if [ $? = 0 ]; then
        echo "Podman was found"
        docker=$podman
else
        podman="missing"
fi

if [ "$docker" = "missing" ] && [ "$podman" = "missing" ]; then
	echo "Docker and Podman are missing. We need at least one! exiting..."
	exit 1
fi


echo
echo "Script to run: $script"
echo
