#!/bin/bash


# find docker
docker=$(which docker 2> /dev/null)
if [ $? = 0 ]; then
	docker=$docker
else
	podman=$(which podman 2> /dev/null)
	if [  $? = 0 ]; then
		docker=$podman
	else
		echo "ERROR: Docker or Podman are required, exiting..."
		exit 1
	fi
fi

echo
echo "Docker found at: $docker"
echo


# build debian docker environment
#echo "Building docker environment..."
#echo
#$docker build --format=docker -t debian-env /mnt/cerebrum/development/phvalheim-client/git/builders/dockers/debian/.


# pull pre-built docker environment
echo "Pulling pre-built debian environment..."
echo
$docker image pull docker.io/theoriginalbrian/debian-env:latest


# run tgz build logic inside the container we just built
echo "Building tarball inside container..."
echo
$docker run -v '/mnt/cerebrum/development/phvalheim-client/git':'/git' -ti debian-env /git/builders/build_tgz-innie

# cleaning docker images
echo "Cleaning up..."
echo
images=$($docker ps -a|grep docker.io/theoriginalbrian/debian-env|cut -d " " -f1)
for i in $images; do
	$docker rm -f $i
done
